version: '3'

services:
  app:
    container_name: art_admin_panel_app
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/app/dev.Dockerfile
    environment:
      - APP_ENV=local
      - LANG=fr_FR.UTF-8
      - PORT=8000
    ports:
      - 8000:8000
    volumes:
      - '../:/home/app'
      - './app/.env:/home/app/.env'
      - '/home/app/node_modules'
    networks:
      - app-network

  art_admin_panel_db:
    image: postgres:15
    container_name: art_admin_panel_db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
    volumes:
      - db_art_admin_panel_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_art_admin_panel_data:

networks:
  app-network:
    driver: bridge
